### ISSUE TITLE
support for 7.6?

### ISSUE THREAD

**Issue by avan2s** [camunda/camunda-bpm-platform-osgi#40]
we would like to use Camunda version 7.6 in an OSGI context. Currently the Camunda OSGI bundle1 is only supporting version 7.5. Is there a way to bring it to work with version 7.6?

**Comment by rbraeunlich** [comment]
Hi @avan2s 
I'm currently quite busy, therefore I didn't manage to follow the camunda BPM releases.
Feel free to open a pull request with 7.6 support. We'll then merge and release it.
Basically, you just have to update the dependencies to the appropriate version, check for compile errors and see if the tests pass. The Karaf feature.xml and the `OSGiTestEnvironment.java` might need some manual adjustments in order to set the correct versions of the transitive dependencies. If you have any questions, feel free to ask.
Cheers,
Ronny

**Comment by rbraeunlich** [comment]
See #44
