### ISSUE TITLE
Passing Business Key through subprocess does not work correctly

### ISSUE THREAD

**Issue by avan2s** [camunda/camunda-bpm-platform-osgi#42]
Hello,
as i described [here](https://forum.camunda.org/t/getting-all-tasks-by-processinstanceid-including-those-in-subprocesses/3184) in the forum, i need all tasks in a processinstance and all of its child. Therefore Camunda is using the businessKey for that, that the engine is passing through all the nested subprocesses. In the Camunda Modeler you have to click on the businessKey-checkbox or put the following in the bpmn file:

```
<callActivity id="callSubProcess" calledElement="checkCreditProcess" >
  <extensionElements>
    <camunda:in businessKey="#{execution.processBusinessKey}" />
  </extensionElements>
</callActivity>
```
https://docs.camunda.org/manual/7.5/reference/bpmn20/subprocesses/call-activity/

In spring environment it is working fine and the business key is forwarded through the subprocess, but in the OSGI-version  i got an exception, that the property execution.processBusinessKey was not found. Is there a seperate file in the osgi-version, which overwrites this standard behavour? What can i do to bring this to work?

Best regards
Andy

**Comment by rbraeunlich** [comment]
Hi Andy,
I gotta admit that I am not familiar with business keys. Would it be possible that you show me the whole stacktrace or write a unit test that triggers the exception?
Cheers,
Ronny

**Comment by rbraeunlich** [comment]
Hi Andy,
I've finally found time to take a look into your problem. Passing the business key to the subprocess (or better CallActivity) works, you just have to be careful, which ElResolver you use. Using the OSGiElResolver, the business key just works. Strangely, in my initial test I've had the problem that BeanUtils was missing and the exception was not logged properly, but that's related to the core engine
Nevertheless, keep in mind that you can always set your own ExpressionManager at the ProcessEngineConfiguration.
Cheers,
Ronny

**Comment by avan2s** [comment]
Hi Ronny,
thank you for taking this problem into account and thanks for the solution. I am a little bit confused about the different EL Resolvers and EL Managers.  What is it's responsiblity? I know that it has something to do with all the expressions like ${abc}, but i don't exactly now, what it is doing. When should i use the OSGIElResolver and when the BlueprintELResolver? Are there differences?
Cheers, 
Andy

**Comment by rbraeunlich** [comment]
Hi Andy,
among other things, the `ExpressionManager` provides an `ElResolver`. I'll only talk about the `ElResolver` here because I never came in touch with the other things and don't exactly know what they are.
If you take a look into the [OSGiExpressionManager](https://github.com/camunda/camunda-bpm-platform-osgi/blob/master/camunda-bpm-osgi/src/main/java/org/camunda/bpm/extension/osgi/el/OSGiExpressionManager.java) you can see that it provides a `CompositeElResolver`. That one simply takes several `ElResolver` and tries them all. 
The basic ones are `ArrayELResolver`, `ListELResolver` and `MapELResolver`. They are basically concerned with how you write an array, list or map directly inside of `${...}`.
Special in the OSGi environment are the two you already mentioned. They are also referenced [here](https://github.com/camunda/camunda-bpm-platform-osgi#part-4-referencing-inside-processes). I'd recommend using the `OSGiElResolver` because it covers more ways to reference a bean. The `BlueprintElResolver` only works with `JavaDelegates` but has most probably a better performance, because it does not search all services for matching names.
Lastly, in the special case of this bug, the [BeanELResolver](https://github.com/camunda/camunda-bpm-platform/blob/master/engine/src/main/java/org/camunda/bpm/engine/impl/javax/el/BeanELResolver.java) could have solved the problem, too. It follows the JavaBean specification when trying to resolve expressions. But I do not want to include it in the `OSGiExpressionManager` because it could cause other problems.
Finally, as already mentioned, you could instantiate your own `CompositeElResolver` and give it the ElResolvers you wanna use. Then, pass it to your configuration inside an `ExpressionManager`.
Cheers,
Ronny
