### ISSUE TITLE
Missing Bundles for using Blueprint and OSGiProcessApplication

### ISSUE THREAD

**Issue by LinaSchad** [camunda/camunda-bpm-platform-osgi#53]
Hi, 

till the recent update I used the camunda-bpm-karaf-feature-minimal to install Camunda into Karaf because I had issues with the full feature due to problems with the spring source bundles. I was able to install it now, so whatever you did, thanks for that. 

Besides, I need to have the BPMNs together with the additional implementations separated from a bundle that starts a process instance and I'm achieving this by using Blueprint and a class that extends the OSGiProcessApplication class in the bundle with the bpmns. Even with the full feature there are some bundles missing for me. To be specific these bundles are missing:

- camunda-bpm-osgi-porcessapplication/5.0.0
- org.apache.aries.transaction.blueprint/2.2.0
- org.apache.aries.proxy/1.1.2
- org.apache.aries.blueprint.core/1.10.0
- org.apache.aries.blueprint.api/1.0.1

Did you decide to not include them on purpose or did you just happen to never have a need for them?
Cheers,
Lina

**Comment by rbraeunlich** [comment]
Hi Lina,

from whtat I can remember the Aries bundles were never included because I expected them to be part of every Karaf. Therefore, they were never included. Does your Karaf have never versions of those or are they missing completely? And which Karaf version are you using? Or do you use a custom one?
Regarding the OSGi ProcessApplication bundle it's a little complicated. The `camunda-core` feature inside the `feature.xml` only contains the base bundle, camunda-bpm-osgi. I never only wanted to provide this as the foundation, since it's the bare minimum. E.g. using the ConfigAdmin bundle doesn't mean you want the Eventing, too. I could create a feature that contains all camunda OSGi bundles but that wouldn't help in your case. And creating a feature for every bundle seems overkill.

Cheers,
Ronny

**Comment by LinaSchad** [comment]
Hi,

I'm using the latest Karaf 4.2.1, when I just looked into the release notes the Bundles interestingly they say, that the Aries bundles were updated to the latest version. Still, when I try to install the needed bundles, Karaf keeps on telling me that exactly these bundles are missing. If I don't install them manually I can't install mine.

Regarding the OSGi ProcessApplication that's fair enough and it's not a big deal to install it myself.

Thanks for your reply!

Cheers,
Lina

**Comment by LinaSchad** [comment]
Hi,

sorry for the late reply. 

I see, that does sound like a little more work. The bundle depending on Aries is the Camunda-bpm-osgi-processapplication one. I need to manually install 
- mvn:org.apache.aries.transaction/org.apache.aries.transaction.blueprint/2.2.0
- mvn:org.apache.aries.blueprint/org.apache.aries.blueprint.core/1.10.0
- mvn:org.apache.aries.proxy/org.apache.aries.proxy/1.1.2
- mvn:org.apache.aries.blueprint/org.apache.aries.blueprint.api/1.0.1

After that everything works like a charm.

Cheers,
Lina

**Comment by rbraeunlich** [comment]
Hi @LinaSchad 

this makes sense. ProcessApplication uses Blueprint internally. Looks like the required enterprise OSGi version doesn't match Karaf's anymore. I will close this issue and create three follow up tasks to update OSGi core, enterprise and Karaf.

Cheers,
Ronny
